[[dependency]]
org = "ballerina"
name = "log"
version = "1.1.0-alpha5"

[[dependency]]
org = "ballerina"
name = "test"
version = "0.0.0"

[[dependency]]
org = "ballerina"
name = "io"
version = "0.6.0-alpha5"

[[dependency]]
org = "ballerina"
name = "random"
version = "0.10.0-alpha5"

[[dependency]]
org = "ballerina"
name = "observe"
version = "0.9.0"

[[dependency]]
org = "ballerina"
name = "file"
version = "0.7.0-alpha5"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "1.1.0-alpha5"


